language: cpp
compiler: g++


before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq



install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq  cmake
 - sudo apt-get upgrade
 - sudo apt-get install build-essential
 - wget https://cmake.org/files/v3.4/cmake-3.4.3.tar.gz
 - tar xf cmake-3.4.3.tar.gz
 - cd cmake-3.4.3
 - ./configure
 - make -j8
 - sudo make install
 - export PATH=/usr/local/bin:$PATH
 - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH


before_script:
- cmake --version
- gcc --version
- g++ --version


script:
- cd DSL
- mkdir -p build 
- cd build 
- cmake ..
- make -j4
