language: cpp
compiler: g++


before_install:




install:
 
 - export PATH=/usr/local/bin:$PATH
 - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH


before_script:
- cmake --version
- gcc --version
- g++ --version
- echo `pwd`
- cd DSL


script:
- cd DSL
- mkdir -p build 
- cd build 
- cmake ..
- make -j4
