language: cpp
compiler: g++


before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
 - sudo apt-get update -qq



install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq  cmake
 - sudo apt-get upgrade


before_script:
- cmake --version
- gcc --version
- g++ --version


script:
- cd DSL
- mkdir -p build 
- cd build 
- cmake ..
- make -j4
