language: cpp
compiler: 
- g++
- clang


before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq


install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq  cmake


before_script:
- cmake --version
- gcc --version
- g++ --version


script:
- cd DSL
- mkdir -p build 
- cd build 
- cmake ..
- make -j4
