language: cpp
compiler: clang++


before_install:
- sudo add-apt-repository  ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
 
# gtest install workaround
- BASE=`pwd`
- git clone https://github.com/google/googletest.git
- cd googletest
- cmake .
- make
- sudo make install
- cd $BASE
# -- workaround end




install:
 - sudo apt-get install build-essential
 - sudo apt-get install -qq g++-4.8
 - export CXX="g++-4.8"
 - wget --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.3.tar.gz
 - tar xf cmake-3.4.3.tar.gz
 - cd cmake-3.4.3
 - ./configure
 - make 
 - sudo make install
 - export PATH=/usr/local/bin:$PATH
 - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH


before_script:
- cmake --version
- gcc --version
- g++ --version



script:
- export CXX="clang++"
- echo `ls -lah`
- echo `pwd`
- mkdir -p build 
- cd build 
- cmake ../../DSL/
- make 
